AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 40
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
